# syntax=docker/dockerfile:1

FROM python:3.10-slim-buster

WORKDIR /app

COPY iot/install/requirements.txt requirements.txt
RUN apt update
RUN apt-get install -y rpi.gpio \
                    gcc build-essential

RUN pip3 install -r requirements.txt
COPY ./iot .

CMD [ "tail", "-f", "/dev/null"]