# syntax=docker/dockerfile:1

FROM --platform=$TARGETPLATFORM python:3.10-slim-buster

WORKDIR /ae-iot/iot
ENV TZ=Europe/Oslo

COPY install/requirements.txt requirements.txt
RUN apt-get update -y
RUN apt-get install -y \
                    gcc build-essential \
                    cron \
                    nano

RUN pip3 install -r requirements.txt

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

CMD [ "tail", "-f", "/var/log/cron.log"]
