version: '3.7'

services:
  aeiot:
      build:
          context: ..
          dockerfile: .devcontainer/Dockerfile
      privileged: true
      environment:
          PORT: 5000
      hostname: aeiot
      networks:
        - iot
      ports:
          - 5000:5000
      volumes:
          - ..:/workspace
      devices:
        - /dev/mem:/dev/mem
      # user: vscode
      command: sleep infinity


  redis:
    image: redis
    hostname: redis
    container_name: redis
    networks:
      - iot
    expose:
      - 6379
    restart: unless-stopped
    environment:
      - TZ=Europe/Oslo

networks:
  iot:
    driver: bridge